ERROR	2022/11/05 21:15:28 main.go:144: failed to connect to `host=localhost user=hadon database=`: failed SASL auth (FATAL: password authentication failed for user "hadon" (SQLSTATE 28P01))
ERROR	2022/11/05 21:15:50 main.go:144: failed to connect to `host=localhost user=hadon database=`: failed SASL auth (FATAL: password authentication failed for user "hadon" (SQLSTATE 28P01))
ERROR	2022/11/05 21:18:31 main.go:138: failed to connect to `host=localhost user=hadon database=`: failed SASL auth (FATAL: password authentication failed for user "hadon" (SQLSTATE 28P01))
ERROR	2022/11/05 21:18:57 main.go:138: failed to connect to `host=localhost user=hadon database=`: failed SASL auth (FATAL: password authentication failed for user "hadon" (SQLSTATE 28P01))
ERROR	2022/11/05 21:19:22 main.go:138: failed to connect to `host=localhost user=hadon database=`: failed SASL auth (FATAL: password authentication failed for user "hadon" (SQLSTATE 28P01))
ERROR	2022/11/05 21:19:28 main.go:138: failed to connect to `host=localhost user=hadon database=`: failed SASL auth (FATAL: password authentication failed for user "hadon" (SQLSTATE 28P01))
ERROR	2022/11/05 21:21:42 main.go:138: failed to connect to `host=postgres user=postgres database=cycir`: hostname resolving error (lookup postgres: context deadline exceeded)
ERROR	2022/11/05 21:24:56 main.go:139: failed to connect to `host=localhost user=postgres database=cycir`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))
ERROR	2022/11/05 21:25:08 main.go:139: failed to connect to `host=localhost user=postgres database=cycir`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))
ERROR	2022/11/05 21:25:14 main.go:139: failed to connect to `host=localhost user=postgres database=cycir`: server error (FATAL: the database system is starting up (SQLSTATE 57P03))
ERROR	2022/11/06 21:38:56 main.go:138: failed to connect to `host=localhost user=hadon database=`: failed SASL auth (FATAL: password authentication failed for user "hadon" (SQLSTATE 28P01))
ERROR	2022/11/06 21:38:58 main.go:138: failed to connect to `host=localhost user=hadon database=`: failed SASL auth (FATAL: password authentication failed for user "hadon" (SQLSTATE 28P01))
